drkiq/config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'welcome', to: 'pages#welcome'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

drkiq/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

drkiq/app/models/reason.rb
class Reason < ApplicationRecord
end

drkiq/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

drkiq/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @meaning_of_life = CounterJob.perform_now
  end

  def welcome
    @json_var = JSON.parse('{"welcome_package": {"turkey": true, "spaghetti": true, "milk cream": true}}')
    respond_to do |format|
      format.html
    end
  end

end

drkiq/app/helpers/application_helper.rb
module ApplicationHelper
end

drkiq/app/helpers/pages_helper.rb
module PagesHelper
end

drkiq/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Drkiq</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

drkiq/app/views/pages/home.html.erb
<h1>Pages#home</h1>
<h1 class="meaning-of-life">The meaning of life is <%= @meaning_of_life %></h1>

<%= link_to 'Surpresa', welcome_path %>

drkiq/app/views/pages/welcome.html.erb
<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>

<h2> A surpresa </h2>
<ul>
  <% @json_var.values.first.each do |key, value| %>
  <li> <%= key %> => <%= value %> </li>
  <% end %>
</ul>